"use client";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { api, errorText } from "@/lib/api";
import { Dialog, ErrorNote } from "@/components/ui";
import type { WorkspaceProject } from "@/lib/workspace-files";
export function WorkspaceProjectControl({ workspaceId, conversationId, projectId, canWrite }: { workspaceId: string; conversationId: string; projectId?: string | null; canWrite: boolean }) {
  const queryClient = useQueryClient(), base = `/api/v1/workspaces/${workspaceId}`;
  const projects = useQuery({ queryKey: ["workspace-projects", workspaceId], queryFn: () => api<WorkspaceProject[]>(`${base}/projects`) });
  const [open, setOpen] = useState(false), [editingId, setEditingId] = useState<string | null>(null), [name, setName] = useState(""), [description, setDescription] = useState(""), [repository, setRepository] = useState(""), [revision, setRevision] = useState(""), [context, setContext] = useState("");
  const [busy, setBusy] = useState(false), [error, setError] = useState<string | null>(null);
  const [savedSource, setSavedSource] = useState<{ source_revision: string; excluded: string[] } | null>(null);
  const selected = projects.data?.find((project) => project.id === projectId);
  const bind = async (id: string | null) => { await api(`${base}/conversations/${conversationId}`, { method: "PATCH", body: { project_id: id } }); await queryClient.invalidateQueries({ queryKey: ["conversation", workspaceId, conversationId] }); };
  const action = async (operation: () => Promise<void>) => { setBusy(true); setError(null); try { await operation(); } catch (failure) { setError(errorText(failure, "Couldn't update the project.")); } finally { setBusy(false); } };
  const edit = (project?: WorkspaceProject) => { setEditingId(project?.id ?? null); setName(project?.name ?? ""); setDescription(project?.description ?? ""); setRepository(project?.repository_url ?? ""); setRevision(project?.source_revision ?? ""); setContext(project?.context ?? ""); setOpen(true); };
  const save = () => action(async () => {
    const result = await api<WorkspaceProject>(`${base}/projects${editingId ? `/${editingId}` : ""}`, { method: editingId ? "PATCH" : "POST", body: { name, description, repository_url: repository || null, source_revision: revision || null, context } });
    await queryClient.invalidateQueries({ queryKey: ["workspace-projects", workspaceId] }); await bind(result.id); setOpen(false);
  });
  const saveSource = () => action(async () => {
    if (!selected) return;
    const result = await api<{ source_revision: string; excluded: string[] }>(`${base}/projects/${selected.id}/source`, { method: "POST", body: { conversation_id: conversationId } });
    setSavedSource(result); await queryClient.invalidateQueries({ queryKey: ["workspace-projects", workspaceId] });
  });
  return <div className="border-b border-line p-3 text-xs"><div className="flex flex-wrap items-center gap-2"><label className="flex min-w-0 flex-1 items-center gap-2 text-dim">Project<select aria-label="Chat project" value={projectId ?? ""} disabled={!canWrite || busy} onChange={(event) => void action(() => bind(event.target.value || null))} className="min-w-0 flex-1 rounded-lg border border-line bg-surface p-2"><option value="">No project</option>{projects.data?.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label>{canWrite ? <><button type="button" onClick={() => edit()} className="rounded-lg border border-line p-2">New</button>{selected ? <button type="button" onClick={() => edit(selected)} className="rounded-lg border border-line p-2">Edit</button> : null}</> : null}</div>{selected && canWrite ? <button type="button" disabled={busy} onClick={() => void saveSource()} className="mt-2 rounded-lg border border-line p-2">Save this workspace as project source</button> : null}{savedSource ? <div role="status" className="mt-2 break-all text-dim">Saved source {savedSource.source_revision}{savedSource.excluded.length ? <details><summary>{savedSource.excluded.length} excluded files</summary><pre className="whitespace-pre-wrap">{savedSource.excluded.join("\n")}</pre></details> : null}</div> : null}<ErrorNote message={error} /><Dialog title={editingId ? "Edit project" : "Create project"} open={open} onClose={() => setOpen(false)} footer={<button type="submit" form="workspace-project-form" disabled={busy || !name.trim()} className="rounded-lg bg-accent px-4 py-2 text-sm text-white disabled:opacity-40">Save project</button>}><form id="workspace-project-form" onSubmit={(event) => { event.preventDefault(); void save(); }} className="space-y-3"><ErrorNote message={error} />{[{ label: "Name", value: name, set: setName }, { label: "Description", value: description, set: setDescription }, { label: "Repository URL", value: repository, set: setRepository }, { label: "Source revision", value: revision, set: setRevision }].map((field) => <label key={field.label} className="block text-sm">{field.label}<input value={field.value} onChange={(event) => field.set(event.target.value)} className="mt-1 w-full rounded-lg border border-line bg-surface p-2" /></label>)}<label className="block text-sm">Reusable project context<textarea value={context} onChange={(event) => setContext(event.target.value)} rows={5} className="mt-1 w-full rounded-lg border border-line bg-surface p-2" /></label><p className="text-xs text-dim">Project context is reused by chats assigned to this project. Each chat keeps its own working files.</p></form></Dialog></div>;
}
