"use client";
import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Folder, File } from "lucide-react";
import { api, errorText } from "@/lib/api";
import { conversationPath } from "@/lib/workspace-runtime";
import { fileSize } from "@/lib/workspace-files";
import { ErrorNote } from "@/components/ui";
interface DirectoryEntry { path: string; name: string; kind: "file" | "directory"; size_bytes: number | null; }
export function WorkspaceBrowser({ workspaceId, conversationId, canPublish, onOpen }: { workspaceId: string; conversationId: string; canPublish: boolean; onOpen: (path: string) => Promise<void> }) {
  const [path, setPath] = useState(""), [opened, setOpened] = useState(false), [busy, setBusy] = useState<string | null>(null), [error, setError] = useState<string | null>(null);
  const files = useQuery({ queryKey: ["workspace-directory", workspaceId, conversationId, path], queryFn: () => api<{ items: DirectoryEntry[]; path: string; truncated: boolean; omitted: number }>(`${conversationPath(workspaceId, conversationId)}/runtime/files`, { params: { path } }), enabled: opened, retry: false });
  const openFile = async (value: string) => { setBusy(value); setError(null); try { await onOpen(value); } catch (failure) { setError(errorText(failure, "Couldn't open this workspace file.")); } finally { setBusy(null); } };
  return <details className="mb-4 rounded-lg border border-line" onToggle={(event) => setOpened(event.currentTarget.open)}><summary className="cursor-pointer p-3 text-sm font-medium">Working directory</summary><div className="space-y-2 border-t border-line p-2"><div className="flex items-center gap-2 text-xs"><button type="button" disabled={!path} onClick={() => setPath(path.split("/").slice(0, -1).join("/"))} className="rounded border border-line px-2 py-1 disabled:opacity-40">Up</button><span className="min-w-0 flex-1 break-all font-mono">/workspace{path ? `/${path}` : ""}</span><button type="button" disabled={files.isFetching} onClick={() => void files.refetch()} className="rounded border border-line px-2 py-1">Refresh</button></div><ErrorNote message={error || (files.isError ? errorText(files.error, "Couldn't read this directory.") : null)} />{files.isPending ? <p className="p-2 text-xs text-dim">Reading directory…</p> : <ul>{files.data?.items.map((entry) => <li key={entry.path}><button type="button" disabled={!!busy || (entry.kind === "file" && !canPublish)} onClick={() => entry.kind === "directory" ? setPath(entry.path) : void openFile(entry.path)} className="flex min-h-10 w-full items-center gap-2 rounded p-2 text-left text-xs hover:bg-hover disabled:opacity-50">{entry.kind === "directory" ? <Folder size={15} /> : <File size={15} />}<span className="min-w-0 flex-1 truncate">{entry.name}</span><span className="text-faint">{busy === entry.path ? "Opening…" : entry.kind === "file" ? fileSize(entry.size_bytes ?? 0) : ""}</span></button></li>)}</ul>}{files.data?.truncated ? <p className="text-xs text-warn">Showing up to 256 entries. Open a subdirectory or publish a known path below.</p> : null}{files.data?.omitted ? <p className="text-xs text-dim">System folders, environment files, and symbolic links are omitted.</p> : null}{!canPublish ? <p className="text-xs text-dim">Members can open working files. Published files below are available to view and download.</p> : null}</div></details>;
}
