"""jhin-tools: the tool gateway — the single authorization path for every
agent tool call (plan section 12) — plus the Phase 4 built-in system tools."""

from jhin_tools.builtin import (
    BUILTIN_TOOLS,
    DELEGATION_REPORTING_TOOLS,
    DynamicToolSource,
    ToolCatalog,
    ToolDefinitionCatalog,
    ToolExecutionContext,
    advertised_description,
    allowed_tool_definitions,
    build_builtin_catalog,
    builtin_tool_definitions,
    task_expects_a_reported_result,
    task_scoped_tool_definitions,
)
from jhin_tools.errors import ToolExecutionError
from jhin_tools.gateway import (
    GatewayOutcome,
    GatewayStateError,
    ToolGateway,
)
from jhin_tools.invocation import (
    MAX_TOOL_CALLS_PER_STEP,
    MAX_TOOL_STEP_INDEX,
    SYNC_INVOCATION_FORMAT_VERSION,
    SYNC_INVOCATION_NAMESPACE,
    TOOL_INVOCATION_FORMAT_VERSION,
    TOOL_INVOCATION_NAMESPACE,
    stable_sync_invocation_id,
    stable_tool_invocation_id,
)
from jhin_tools.sanitize import (
    INVALID_TOOL_ARGUMENTS_KEY,
    MAX_DOCUMENT_BYTES,
    MAX_STRING_CHARS,
    invalid_tool_arguments,
    invalid_tool_arguments_json,
    sanitize_payload,
)
from jhin_tools.test_barriers import (
    AGENT_BEFORE_BIND,
    PHASE9_AFTER_MANIFEST,
    PHASE9_CLEANUP_BEFORE_EFFECT,
    PHASE9_SYNC_BEFORE_EFFECT,
    TOOL_AFTER_CLAIM,
    TOOL_AFTER_EFFECT,
    TOOL_BEFORE_CLAIM,
    CrashBarrier,
    CrashBarrierConfig,
    CrashBarrierName,
    release_barrier,
)

__all__ = [
    "AGENT_BEFORE_BIND",
    "BUILTIN_TOOLS",
    "DELEGATION_REPORTING_TOOLS",
    "INVALID_TOOL_ARGUMENTS_KEY",
    "MAX_DOCUMENT_BYTES",
    "MAX_STRING_CHARS",
    "MAX_TOOL_CALLS_PER_STEP",
    "MAX_TOOL_STEP_INDEX",
    "PHASE9_AFTER_MANIFEST",
    "PHASE9_CLEANUP_BEFORE_EFFECT",
    "PHASE9_SYNC_BEFORE_EFFECT",
    "SYNC_INVOCATION_FORMAT_VERSION",
    "SYNC_INVOCATION_NAMESPACE",
    "TOOL_AFTER_CLAIM",
    "TOOL_AFTER_EFFECT",
    "TOOL_BEFORE_CLAIM",
    "TOOL_INVOCATION_FORMAT_VERSION",
    "TOOL_INVOCATION_NAMESPACE",
    "CrashBarrier",
    "CrashBarrierConfig",
    "CrashBarrierName",
    "DynamicToolSource",
    "GatewayOutcome",
    "GatewayStateError",
    "ToolCatalog",
    "ToolDefinitionCatalog",
    "ToolExecutionContext",
    "ToolExecutionError",
    "ToolGateway",
    "advertised_description",
    "allowed_tool_definitions",
    "build_builtin_catalog",
    "builtin_tool_definitions",
    "invalid_tool_arguments",
    "invalid_tool_arguments_json",
    "release_barrier",
    "sanitize_payload",
    "stable_sync_invocation_id",
    "stable_tool_invocation_id",
    "task_expects_a_reported_result",
    "task_scoped_tool_definitions",
]
