import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { cleanup, fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";
import ConnectorsPage from "@/app/(app)/connectors/page";
import type { ConnectionInfo, ConnectorInfo, WebhookSetup } from "@/lib/types";
import { WorkspaceProvider } from "@/lib/workspace-context";

const WebhookSecretDialog = ConnectorsPage.WebhookSecretDialog;

afterEach(() => {
  cleanup();
  vi.unstubAllGlobals();
});

const BASE_CONNECTOR: ConnectorInfo = {
  connector_type: "github",
  display_name: "GitHub",
  icon: "github",
  description: "Source control",
  auth_schemes: [{
    type: "pat",
    label: "Personal access token",
    description: "",
    secret_fields: [{
      name: "token",
      label: "Token",
      placeholder: "ghp_…",
      multiline: false,
      required: true,
    }],
  }],
  config_fields: [],
  webhook_events: ["push"],
  canonical_events: [],
  capabilities: ["github.repository.read"],
  supports_webhooks: true,
  webhook_secret_mode: "generated",
  webhook_signature_algorithm: "hmac-sha256",
  webhook_setup_help: "Use this generated secret.",
  docs_url: "",
};

const CONNECTORS: ConnectorInfo[] = [
  BASE_CONNECTOR,
  {
    ...BASE_CONNECTOR,
    connector_type: "linear",
    display_name: "Linear",
    icon: "linear",
    auth_schemes: [{
      type: "api_key",
      label: "Personal API key",
      description: "",
      secret_fields: [{
        name: "api_key",
        label: "API key",
        placeholder: "lin_api_…",
        multiline: false,
        required: true,
      }],
    }],
    capabilities: ["linear.issue.read"],
  },
  {
    ...BASE_CONNECTOR,
    connector_type: "vercel",
    display_name: "Vercel",
    icon: "vercel",
    auth_schemes: [{
      type: "access_token",
      label: "Access token",
      description: "",
      secret_fields: [{
        name: "token",
        label: "Access token",
        placeholder: "Vercel token",
        multiline: false,
        required: true,
      }],
    }],
    capabilities: ["vercel.project.read"],
    webhook_secret_mode: "provider_supplied",
    webhook_signature_algorithm: "hmac-sha1",
    webhook_setup_help: "Paste the secret generated by Vercel.",
  },
  {
    ...BASE_CONNECTOR,
    connector_type: "supabase",
    display_name: "Supabase",
    icon: "supabase",
    auth_schemes: [
      {
        type: "management_token",
        label: "Management API token",
        description: "",
        secret_fields: [{
          name: "access_token",
          label: "Access token",
          placeholder: "Supabase access token",
          multiline: false,
          required: true,
        }],
      },
      {
        type: "postgres",
        label: "PostgreSQL database",
        description: "",
        secret_fields: [{
          name: "database_url",
          label: "Database URL",
          placeholder: "postgresql://…",
          multiline: false,
          required: true,
        }],
      },
    ],
    config_fields: [
      { name: "project_ref", label: "Project reference", required: true, placeholder: "project", help: "", kind: "text", auth_types: ["management_token", "postgres"], default: null, minimum: null, maximum: null },
      { name: "base_url", label: "Management API base URL", required: false, placeholder: "", help: "", kind: "text", auth_types: ["management_token"], default: "https://api.supabase.com", minimum: null, maximum: null },
      { name: "allowed_schemas", label: "Allowed schemas", required: false, placeholder: "", help: "", kind: "string_list", auth_types: ["postgres"], default: ["public"], minimum: null, maximum: null },
      { name: "allow_writes", label: "Allow database writes", required: false, placeholder: "", help: "", kind: "boolean", auth_types: ["postgres"], default: false, minimum: null, maximum: null },
      { name: "max_rows", label: "Maximum rows", required: false, placeholder: "", help: "", kind: "integer", auth_types: ["postgres"], default: 200, minimum: 1, maximum: 1000 },
    ],
    webhook_events: [],
    capabilities: ["supabase.project.read", "supabase.database.read"],
    supports_webhooks: false,
    webhook_secret_mode: "none",
    webhook_signature_algorithm: "",
    webhook_setup_help: "",
  },
];

function json(data: unknown, status = 200): Response {
  return new Response(status === 204 ? null : JSON.stringify(data), {
    status,
    headers: { "content-type": "application/json" },
  });
}

function connectionFor(id: string, connectorType: string, name: string): ConnectionInfo {
  return {
    id,
    connector_type: connectorType,
    name,
    auth_type: connectorType === "linear" ? "api_key" : connectorType === "vercel" ? "access_token" : "pat",
    status: "active",
    public_id: `public-${id}`,
    config_json: {},
    created_by_user_id: "user-1",
    created_at: "2026-08-18T00:00:00Z",
    last_verified_at: null,
    last_error: null,
    webhook_secret_configured: false,
  };
}

function deferred() {
  let resolve!: () => void;
  const promise = new Promise<void>((done) => {
    resolve = done;
  });
  return { promise, resolve };
}

function installServer({ deferWebhookRefetch = false } = {}) {
  const connections: ConnectionInfo[] = [];
  const writes: { path: string; body: Record<string, unknown> }[] = [];
  const webhookRefetch = deferred();
  let webhookStored = false;
  let postWebhookPutGets = 0;
  const fetchMock = vi.fn(async (input: string | URL | Request, init?: RequestInit) => {
    const path = String(input);
    const method = init?.method ?? "GET";
    const body = init?.body ? JSON.parse(String(init.body)) as Record<string, unknown> : {};
    if (path === "/api/v1/connectors") return json(CONNECTORS);
    if (path === "/api/v1/workspaces/workspace-1/connections" && method === "GET") {
      if (webhookStored) {
        postWebhookPutGets += 1;
        if (deferWebhookRefetch && postWebhookPutGets === 1) {
          await webhookRefetch.promise;
        }
      }
      return json(connections);
    }
    if (path === "/api/v1/workspaces/workspace-1/connections" && method === "POST") {
      writes.push({ path, body });
      const connectorType = String(body.connector_type);
      const connection = connectionFor(`conn-${connections.length + 1}`, connectorType, String(body.name));
      connection.auth_type = String(body.auth_type);
      connection.config_json = body.config as Record<string, unknown>;
      connections.push(connection);
      const connector = CONNECTORS.find((entry) => entry.connector_type === connectorType)!;
      return json({
        connection,
        webhook: connector.webhook_secret_mode === "none" ? null : {
          url_path: `/api/v1/webhooks/${connectorType}/${connection.public_id}`,
          secret: connector.webhook_secret_mode === "generated" ? `${connectorType}-generated-secret` : null,
          secret_mode: connector.webhook_secret_mode,
          signature_algorithm: connector.webhook_signature_algorithm,
          help: connector.webhook_setup_help,
        },
      });
    }
    const webhookMatch = path.match(/\/connections\/(conn-\d+)\/webhook-secret$/);
    if (webhookMatch && method === "PUT") {
      writes.push({ path, body });
      connections.find((connection) => connection.id === webhookMatch[1])!.webhook_secret_configured = true;
      webhookStored = true;
      return json(null, 204);
    }
    if (path.endsWith("/tool-calls")) return json([]);
    if (path.endsWith("/access-summary")) {
      return json({ connection_id: path.split("/").at(-2), agents: [] });
    }
    throw new Error(`Unexpected request: ${method} ${path}`);
  });
  vi.stubGlobal("fetch", fetchMock);
  return {
    connections,
    writes,
    releaseWebhookRefetch: webhookRefetch.resolve,
    get postWebhookPutGets() {
      return postWebhookPutGets;
    },
  };
}

function renderPage() {
  const queryClient = new QueryClient({
    defaultOptions: { queries: { retry: false }, mutations: { retry: false } },
  });
  render(
    <QueryClientProvider client={queryClient}>
      <WorkspaceProvider
        user={{ id: "user-1", email: "owner@example.com", display_name: "Owner", created_at: "2026-08-18T00:00:00Z" }}
        workspace={{ workspace_id: "workspace-1", workspace_name: "Acme", workspace_slug: "acme", role: "owner" }}
      >
        <ConnectorsPage />
      </WorkspaceProvider>
    </QueryClientProvider>,
  );
}

function connectButton(type: string): HTMLButtonElement {
  return within(screen.getByTestId(`connector-${type}`)).getByRole("button", { name: "Connect" });
}

describe("ConnectorsPage", () => {
  it("updates provider-secret status before the background refetch completes", async () => {
    const server = installServer({ deferWebhookRefetch: true });
    renderPage();

    await screen.findByTestId("connector-vercel");
    fireEvent.click(connectButton("vercel"));
    const createDialog = await screen.findByRole("dialog", { name: "Connect Vercel" });
    fireEvent.change(within(createDialog).getByPlaceholderText("Vercel (production)"), { target: { value: "Vercel production" } });
    fireEvent.change(within(createDialog).getByPlaceholderText("Vercel token"), { target: { value: "vercel-token" } });
    fireEvent.click(screen.getByRole("button", { name: "Create connection" }));

    await waitFor(() => expect(server.writes).toHaveLength(1));
    const connectionCard = await screen.findByTestId("connection-Vercel production");
    const setupDialog = await screen.findByRole("dialog", { name: "Webhook setup" });
    const secret = within(setupDialog).getByLabelText(/Provider-generated signing secret/);
    fireEvent.change(secret, { target: { value: "provider-secret-1234" } });
    fireEvent.click(screen.getByRole("button", { name: "Store provider secret" }));
    await waitFor(() => expect(screen.queryByRole("dialog", { name: "Webhook setup" })).toBeNull());
    await waitFor(() => expect(server.postWebhookPutGets).toBe(1));

    try {
      fireEvent.click(connectionCard);
      expect(screen.getByText("Webhook secret configured")).toBeDefined();
    } finally {
      server.releaseWebhookRefetch();
    }
  });

  it("clears the provider secret while mounted before closing after cache synchronization", async () => {
    const stored = deferred();
    const onStored = vi.fn(() => stored.promise);
    const onClose = vi.fn();
    const webhook: WebhookSetup = {
      url_path: "/api/v1/webhooks/vercel/public-1",
      secret: null,
      secret_mode: "provider_supplied",
      signature_algorithm: "hmac-sha1",
      help: "Paste the secret generated by Vercel.",
    };
    vi.stubGlobal("fetch", vi.fn(async () => json(null, 204)));
    const queryClient = new QueryClient({
      defaultOptions: { queries: { retry: false }, mutations: { retry: false } },
    });
    render(
      <QueryClientProvider client={queryClient}>
        <WebhookSecretDialog
          workspaceId="workspace-1"
          connectionId="conn-1"
          connectionName="Vercel production"
          webhook={webhook}
          onStored={onStored}
          onClose={onClose}
        />
      </QueryClientProvider>,
    );

    const input = screen.getByLabelText(/Provider-generated signing secret/) as HTMLInputElement;
    fireEvent.change(input, { target: { value: "provider-secret-1234" } });
    fireEvent.click(screen.getByRole("button", { name: "Store provider secret" }));
    await waitFor(() => expect(onStored).toHaveBeenCalledOnce());
    expect(input.value).toBe("");
    expect(onClose).not.toHaveBeenCalled();

    stored.resolve();
    await waitFor(() => expect(onClose).toHaveBeenCalledOnce());
  });

  it("switches Supabase auth planes without leaking inactive config and keeps writes off", async () => {
    const server = installServer();
    renderPage();

    await screen.findByTestId("connector-supabase");
    fireEvent.click(connectButton("supabase"));
    const dialog = await screen.findByRole("dialog", { name: "Connect Supabase" });
    expect(within(dialog).getByPlaceholderText("Supabase access token")).toBeDefined();
    expect(within(dialog).getByDisplayValue("https://api.supabase.com")).toBeDefined();
    expect(within(dialog).queryByPlaceholderText("postgresql://…")).toBeNull();
    fireEvent.change(within(dialog).getByDisplayValue("https://api.supabase.com"), {
      target: { value: "http://management-only" },
    });

    fireEvent.change(within(dialog).getByRole("combobox"), { target: { value: "postgres" } });
    expect(within(dialog).queryByPlaceholderText("Supabase access token")).toBeNull();
    expect(within(dialog).queryByDisplayValue("http://management-only")).toBeNull();
    expect(within(dialog).getByPlaceholderText("postgresql://…")).toBeDefined();
    expect(within(dialog).getByDisplayValue("public")).toBeDefined();
    expect(within(dialog).getByDisplayValue("200")).toBeDefined();
    expect((within(dialog).getByLabelText("Allow database writes") as HTMLInputElement).checked).toBe(false);
    expect(within(dialog).getAllByRole("checkbox")).toHaveLength(1);

    fireEvent.change(within(dialog).getByPlaceholderText("Supabase (production)"), {
      target: { value: "Supabase database" },
    });
    fireEvent.change(within(dialog).getByPlaceholderText("postgresql://…"), {
      target: { value: "postgresql://reader:secret@db/project" },
    });
    fireEvent.change(within(dialog).getByPlaceholderText("project"), {
      target: { value: "project-ref" },
    });
    fireEvent.click(within(dialog).getByRole("button", { name: "Create connection" }));
    await waitFor(() => expect(server.writes).toHaveLength(1));
    expect(server.writes[0].body.config).toEqual({
      project_ref: "project-ref",
      allowed_schemas: ["public"],
      allow_writes: false,
      max_rows: 200,
    });
  });

  it.each([
    ["github", "GitHub", "ghp_…"],
    ["linear", "Linear", "lin_api_…"],
  ])("keeps the %s generated webhook secret in a one-time dialog", async (type, displayName, credentialPlaceholder) => {
    installServer();
    renderPage();

    await screen.findByTestId(`connector-${type}`);
    fireEvent.click(connectButton(type));
    const createDialog = await screen.findByRole("dialog", { name: `Connect ${displayName}` });
    fireEvent.change(within(createDialog).getByPlaceholderText(`${displayName} (production)`), {
      target: { value: `${displayName} production` },
    });
    fireEvent.change(within(createDialog).getByPlaceholderText(credentialPlaceholder), {
      target: { value: "credential" },
    });
    fireEvent.click(within(createDialog).getByRole("button", { name: "Create connection" }));

    const secretDialog = await screen.findByRole("dialog", { name: "Webhook secret — shown once" });
    expect(within(secretDialog).getByText(`${type}-generated-secret`)).toBeDefined();
    expect(within(secretDialog).queryByLabelText(/Provider-generated/)).toBeNull();
    fireEvent.click(within(secretDialog).getByRole("button", { name: "I stored the secret" }));
    await waitFor(() => expect(screen.queryByText(`${type}-generated-secret`)).toBeNull());
  });
});
