"""jhin-policy: capability registry, risk levels, and the pure policy
evaluator (plan sections 12 and 42).

This package performs no I/O. The tool gateway (jhin-tools) loads grants and
rules from the database and calls :func:`evaluate`.
"""

from jhin_policy.agent_defaults import (
    ask_person_grant_specs,
    default_agent_grant_specs,
    memory_grant_specs,
    persona_grant_specs,
)
from jhin_policy.approvals import (
    PRESET_RULES,
    ApprovalPreset,
    capability_rules,
    matching_preset,
    rules_for_preset,
)
from jhin_policy.ask_person import ASK_PERSON_CAPABILITY
from jhin_policy.bundles import (
    BUNDLES,
    AnnotatedGrant,
    Bundle,
    BundlePlan,
    BundleState,
    ConnectionRef,
    GrantProblem,
    GrantSpec,
    Need,
    bundle_by_id,
    bundle_capabilities,
    bundle_state,
    covered_capabilities,
    grant_problem_details,
    grant_problems,
    neutral_problem_text,
    plan_bundle,
)
from jhin_policy.capabilities import (
    FORBIDDEN_CAPABILITY_PREFIXES,
    CapabilityRegistry,
    RegistryError,
    ToolDefinition,
    capability_matches,
    covers_forbidden_capability,
    grant_pattern_problem,
    is_forbidden_capability,
    is_valid_capability,
)
from jhin_policy.delegation import (
    DelegationFacts,
    DelegationSettings,
    delegation_settings,
    evaluate_delegation,
)
from jhin_policy.evaluator import (
    DecisionType,
    Grant,
    GrantEffect,
    PolicyDecision,
    PolicyRule,
    authorizing_allow_grants,
    evaluate,
    result_scope_admits,
    scope_matches,
)
from jhin_policy.identity import (
    IDENTITY_SELF_CAPABILITY,
    MAX_AGENT_NAME_CHARS,
    MAX_AGENT_NAME_WORDS,
    MAX_STORED_NAME_CHARS,
    agent_name_problem,
    identity_grant_specs,
    normalize_agent_name,
    render_safe_agent_name,
)
from jhin_policy.memory import (
    MEMORY_CAPABILITIES,
    MEMORY_PROPOSE_CAPABILITY,
    MEMORY_READ_CAPABILITY,
)
from jhin_policy.personas import PERSONA_SELF_CAPABILITY
from jhin_policy.repositories import (
    is_plain_repository,
    is_repository_pattern,
    repository_covered_by_allow_list,
    repository_matches,
)
from jhin_policy.reviews import (
    REVIEW_REQUEST_CAPABILITY,
    ReviewCondition,
    ReviewConditionKind,
    ReviewContext,
    ReviewDecision,
    ReviewerCandidates,
    ReviewerResolution,
    ReviewerSelector,
    ReviewPolicySpec,
    ReviewRequirement,
    evaluate_review_policies,
    policy_spec_from_row,
    resolve_reviewer,
)
from jhin_policy.risk import RiskLevel, RuleAction
from jhin_policy.skills import (
    SKILLS_CAPABILITIES,
    SKILLS_MANAGE_CAPABILITY,
    SKILLS_READ_CAPABILITY,
)
from jhin_policy.work_requests import (
    DIRECTORY_READ_CAPABILITY,
    WORK_REQUEST_CAPABILITY,
    WORK_RESPOND_CAPABILITY,
    CoordinationSettings,
    WorkRequestDecision,
    WorkRequestFacts,
    collaboration_grant_specs,
    coordination_settings,
    evaluate_work_request,
)

__all__ = [
    "ASK_PERSON_CAPABILITY",
    "BUNDLES",
    "DIRECTORY_READ_CAPABILITY",
    "FORBIDDEN_CAPABILITY_PREFIXES",
    "IDENTITY_SELF_CAPABILITY",
    "MAX_AGENT_NAME_CHARS",
    "MAX_AGENT_NAME_WORDS",
    "MAX_STORED_NAME_CHARS",
    "MEMORY_CAPABILITIES",
    "MEMORY_PROPOSE_CAPABILITY",
    "MEMORY_READ_CAPABILITY",
    "PERSONA_SELF_CAPABILITY",
    "PRESET_RULES",
    "REVIEW_REQUEST_CAPABILITY",
    "SKILLS_CAPABILITIES",
    "SKILLS_MANAGE_CAPABILITY",
    "SKILLS_READ_CAPABILITY",
    "WORK_REQUEST_CAPABILITY",
    "WORK_RESPOND_CAPABILITY",
    "AnnotatedGrant",
    "ApprovalPreset",
    "Bundle",
    "BundlePlan",
    "BundleState",
    "CapabilityRegistry",
    "ConnectionRef",
    "CoordinationSettings",
    "DecisionType",
    "DelegationFacts",
    "DelegationSettings",
    "Grant",
    "GrantEffect",
    "GrantProblem",
    "GrantSpec",
    "Need",
    "PolicyDecision",
    "PolicyRule",
    "RegistryError",
    "ReviewCondition",
    "ReviewConditionKind",
    "ReviewContext",
    "ReviewDecision",
    "ReviewPolicySpec",
    "ReviewRequirement",
    "ReviewerCandidates",
    "ReviewerResolution",
    "ReviewerSelector",
    "RiskLevel",
    "RuleAction",
    "ToolDefinition",
    "WorkRequestDecision",
    "WorkRequestFacts",
    "agent_name_problem",
    "ask_person_grant_specs",
    "authorizing_allow_grants",
    "bundle_by_id",
    "bundle_capabilities",
    "bundle_state",
    "capability_matches",
    "capability_rules",
    "collaboration_grant_specs",
    "coordination_settings",
    "covered_capabilities",
    "covers_forbidden_capability",
    "default_agent_grant_specs",
    "delegation_settings",
    "evaluate",
    "evaluate_delegation",
    "evaluate_review_policies",
    "evaluate_work_request",
    "grant_pattern_problem",
    "grant_problem_details",
    "grant_problems",
    "identity_grant_specs",
    "is_forbidden_capability",
    "is_plain_repository",
    "is_repository_pattern",
    "is_valid_capability",
    "matching_preset",
    "memory_grant_specs",
    "neutral_problem_text",
    "normalize_agent_name",
    "persona_grant_specs",
    "plan_bundle",
    "policy_spec_from_row",
    "render_safe_agent_name",
    "repository_covered_by_allow_list",
    "repository_matches",
    "resolve_reviewer",
    "result_scope_admits",
    "rules_for_preset",
    "scope_matches",
]
