"""Shared domain vocabulary for Jhin.

Deliberately dependency-light (stdlib + uuid-utils only) so every package —
db, events, API, workers — can depend on it without dragging in SQLAlchemy,
Pydantic, or NATS.
"""

from jhin_domain.enums import (
    ACTIVITY_LABELS,
    AGENT_MESSAGE_TYPES,
    APPROVAL_DECIDED_STATUSES,
    RUN_ACTIVE_STATUSES,
    RUN_TERMINAL_STATUSES,
    SANDBOX_JOB_TERMINAL_STATUSES,
    TASK_TERMINAL_STATES,
    ActivityKind,
    ActorType,
    AgentStatus,
    ApprovalStatus,
    AutonomyLevel,
    ConnectionStatus,
    ConversationStatus,
    MessageType,
    MessageVisibility,
    ModelProviderType,
    RecipientType,
    RunStatus,
    SandboxJobStatus,
    SecretType,
    SenderType,
    TaskPriority,
    TaskState,
    ToolCallStatus,
    TriggerActionType,
    TriggerInvocationStatus,
    TriggerType,
    UserStatus,
    WorkspaceRole,
    WorkspaceStatus,
    role_satisfies,
)
from jhin_domain.ids import new_uuid7
from jhin_domain.messages import artifact, structured_content

__all__ = [
    "ACTIVITY_LABELS",
    "AGENT_MESSAGE_TYPES",
    "APPROVAL_DECIDED_STATUSES",
    "RUN_ACTIVE_STATUSES",
    "RUN_TERMINAL_STATUSES",
    "SANDBOX_JOB_TERMINAL_STATUSES",
    "TASK_TERMINAL_STATES",
    "ActivityKind",
    "ActorType",
    "AgentStatus",
    "ApprovalStatus",
    "AutonomyLevel",
    "ConnectionStatus",
    "ConversationStatus",
    "MessageType",
    "MessageVisibility",
    "ModelProviderType",
    "RecipientType",
    "RunStatus",
    "SandboxJobStatus",
    "SecretType",
    "SenderType",
    "TaskPriority",
    "TaskState",
    "ToolCallStatus",
    "TriggerActionType",
    "TriggerInvocationStatus",
    "TriggerType",
    "UserStatus",
    "WorkspaceRole",
    "WorkspaceStatus",
    "artifact",
    "new_uuid7",
    "role_satisfies",
    "structured_content",
]
