"""Shared domain vocabulary for Jhin, and the outbound target policy.

Deliberately dependency-light (stdlib + uuid-utils only) so every package —
db, events, API, workers — can depend on it without dragging in SQLAlchemy,
Pydantic, or NATS. That is also what :mod:`jhin_domain.endpoints` is doing
this far down: the OAuth core and the connectors need the same fail-closed
validator, and reaching it through ``jhin_connectors`` would put an executable
connector inside the agent worker.
"""

from jhin_domain.activity import activity_phrase, waiting_for_colleague_phrase
from jhin_domain.endpoints import (
    EndpointPolicyError,
    validate_http_origin,
    validate_postgres_target,
    validate_public_http_url,
)
from jhin_domain.enums import (
    ACTIVITY_LABELS,
    AGENT_MESSAGE_TYPES,
    AVATAR_COLORS,
    AVATAR_GENERATION_TERMINAL_STATUSES,
    AVATAR_SHAPES,
    MEMORY_RETRIEVABLE_STATUSES,
    MEMORY_SCOPE_ORDER,
    REVIEW_BLOCKING_MODES,
    RUN_ACTIVE_STATUSES,
    RUN_TERMINAL_STATUSES,
    TASK_TERMINAL_STATES,
    WORK_REQUEST_ACTIVE_STATUSES,
    WORK_REQUEST_OPEN_STATUSES,
    ActivityKind,
    ActorType,
    AgentStatus,
    ApprovalStatus,
    AutonomyLevel,
    AvatarGenerationStatus,
    AvatarKind,
    ConnectionStatus,
    ConversationStatus,
    MediaAssetStatus,
    MemoryKind,
    MemoryScope,
    MemorySensitivity,
    MemoryStatus,
    MessageType,
    MessageVisibility,
    ModelProviderType,
    RecipientType,
    ReviewerType,
    ReviewMode,
    ReviewScopeKind,
    ReviewVerdict,
    RunStatus,
    SandboxJobStatus,
    SecretType,
    SenderType,
    TaskPriority,
    TaskState,
    ToolCallStatus,
    TriggerActionType,
    TriggerInvocationStatus,
    TriggerType,
    UserQuestionStatus,
    UserStatus,
    WorkRequestStatus,
    WorkReviewStatus,
    WorkspaceRole,
    WorkspaceStatus,
    role_satisfies,
)
from jhin_domain.ids import new_uuid7
from jhin_domain.messages import artifact, structured_content
from jhin_domain.scopes import (
    ALL_SCOPE_KEYS,
    CATEGORIES,
    CATEGORY_BY_KEY,
    CATEGORY_SCOPES,
    GRANTABLE_SCOPE_KEYS,
    SCOPE_BY_KEY,
    SCOPES,
    ScopeCategory,
    ScopeDefinition,
    effective_scopes,
    expand_scopes,
    is_known_scope,
    scopes_above_role,
    scopes_for_role,
)

__all__ = [
    "ACTIVITY_LABELS",
    "AGENT_MESSAGE_TYPES",
    "ALL_SCOPE_KEYS",
    "AVATAR_COLORS",
    "AVATAR_GENERATION_TERMINAL_STATUSES",
    "AVATAR_SHAPES",
    "CATEGORIES",
    "CATEGORY_BY_KEY",
    "CATEGORY_SCOPES",
    "GRANTABLE_SCOPE_KEYS",
    "MEMORY_RETRIEVABLE_STATUSES",
    "MEMORY_SCOPE_ORDER",
    "REVIEW_BLOCKING_MODES",
    "RUN_ACTIVE_STATUSES",
    "RUN_TERMINAL_STATUSES",
    "SCOPES",
    "SCOPE_BY_KEY",
    "TASK_TERMINAL_STATES",
    "WORK_REQUEST_ACTIVE_STATUSES",
    "WORK_REQUEST_OPEN_STATUSES",
    "ActivityKind",
    "ActorType",
    "AgentStatus",
    "ApprovalStatus",
    "AutonomyLevel",
    "AvatarGenerationStatus",
    "AvatarKind",
    "ConnectionStatus",
    "ConversationStatus",
    "EndpointPolicyError",
    "MediaAssetStatus",
    "MemoryKind",
    "MemoryScope",
    "MemorySensitivity",
    "MemoryStatus",
    "MessageType",
    "MessageVisibility",
    "ModelProviderType",
    "RecipientType",
    "ReviewMode",
    "ReviewScopeKind",
    "ReviewVerdict",
    "ReviewerType",
    "RunStatus",
    "SandboxJobStatus",
    "ScopeCategory",
    "ScopeDefinition",
    "SecretType",
    "SenderType",
    "TaskPriority",
    "TaskState",
    "ToolCallStatus",
    "TriggerActionType",
    "TriggerInvocationStatus",
    "TriggerType",
    "UserQuestionStatus",
    "UserStatus",
    "WorkRequestStatus",
    "WorkReviewStatus",
    "WorkspaceRole",
    "WorkspaceStatus",
    "activity_phrase",
    "artifact",
    "effective_scopes",
    "expand_scopes",
    "is_known_scope",
    "new_uuid7",
    "role_satisfies",
    "scopes_above_role",
    "scopes_for_role",
    "structured_content",
    "validate_http_origin",
    "validate_postgres_target",
    "validate_public_http_url",
    "waiting_for_colleague_phrase",
]
