"""Shared domain vocabulary for Jhin.

Deliberately dependency-light (stdlib + uuid-utils only) so every package —
db, events, API, workers — can depend on it without dragging in SQLAlchemy,
Pydantic, or NATS.
"""

from jhin_domain.enums import (
    ACTIVITY_LABELS,
    AGENT_MESSAGE_TYPES,
    AVATAR_GENERATION_TERMINAL_STATUSES,
    MEMORY_RETRIEVABLE_STATUSES,
    MEMORY_SCOPE_ORDER,
    REVIEW_BLOCKING_MODES,
    RUN_ACTIVE_STATUSES,
    RUN_TERMINAL_STATUSES,
    TASK_TERMINAL_STATES,
    WORK_REQUEST_ACTIVE_STATUSES,
    WORK_REQUEST_OPEN_STATUSES,
    ActivityKind,
    ActorType,
    AgentStatus,
    ApprovalStatus,
    AutonomyLevel,
    AvatarGenerationStatus,
    AvatarKind,
    ConnectionStatus,
    ConversationStatus,
    MediaAssetStatus,
    MemoryKind,
    MemoryScope,
    MemorySensitivity,
    MemoryStatus,
    MessageType,
    MessageVisibility,
    ModelProviderType,
    RecipientType,
    ReviewerType,
    ReviewMode,
    ReviewScopeKind,
    ReviewVerdict,
    RunStatus,
    SandboxJobStatus,
    SecretType,
    SenderType,
    TaskPriority,
    TaskState,
    ToolCallStatus,
    TriggerActionType,
    TriggerInvocationStatus,
    TriggerType,
    UserStatus,
    WorkRequestStatus,
    WorkReviewStatus,
    WorkspaceRole,
    WorkspaceStatus,
    role_satisfies,
)
from jhin_domain.ids import new_uuid7
from jhin_domain.messages import artifact, structured_content

__all__ = [
    "ACTIVITY_LABELS",
    "AGENT_MESSAGE_TYPES",
    "AVATAR_GENERATION_TERMINAL_STATUSES",
    "MEMORY_RETRIEVABLE_STATUSES",
    "MEMORY_SCOPE_ORDER",
    "REVIEW_BLOCKING_MODES",
    "RUN_ACTIVE_STATUSES",
    "RUN_TERMINAL_STATUSES",
    "TASK_TERMINAL_STATES",
    "WORK_REQUEST_ACTIVE_STATUSES",
    "WORK_REQUEST_OPEN_STATUSES",
    "ActivityKind",
    "ActorType",
    "AgentStatus",
    "ApprovalStatus",
    "AutonomyLevel",
    "AvatarGenerationStatus",
    "AvatarKind",
    "ConnectionStatus",
    "ConversationStatus",
    "MediaAssetStatus",
    "MemoryKind",
    "MemoryScope",
    "MemorySensitivity",
    "MemoryStatus",
    "MessageType",
    "MessageVisibility",
    "ModelProviderType",
    "RecipientType",
    "ReviewMode",
    "ReviewScopeKind",
    "ReviewVerdict",
    "ReviewerType",
    "RunStatus",
    "SandboxJobStatus",
    "SecretType",
    "SenderType",
    "TaskPriority",
    "TaskState",
    "ToolCallStatus",
    "TriggerActionType",
    "TriggerInvocationStatus",
    "TriggerType",
    "UserStatus",
    "WorkRequestStatus",
    "WorkReviewStatus",
    "WorkspaceRole",
    "WorkspaceStatus",
    "artifact",
    "new_uuid7",
    "role_satisfies",
    "structured_content",
]
