"""A validation-error handler that does not echo the rejected input back.

FastAPI's default handler serialises ``exc.errors()``, and Pydantic v2 puts the
offending value in the ``input`` key of every error. On a route such as
``POST /api/v1/secrets`` — whose ``value`` field carries an API key or a
database password — an over-long or wrong-typed submission therefore returns
the credential itself in the 422 body, where it lands in the browser console,
proxy logs, and error trackers.

The handler below keeps everything a client needs to fix its request (which
field, why) and drops the value and the exception context that can quote it.
"""

from __future__ import annotations

from typing import Any

from fastapi import Request
from fastapi.exceptions import RequestValidationError
from starlette.responses import JSONResponse


def _safe_error(error: Any) -> dict[str, Any]:
    if not isinstance(error, dict):  # pragma: no cover - defensive
        return {"type": "value_error", "loc": [], "msg": "Invalid value"}
    location = error.get("loc", ())
    return {
        "type": str(error.get("type", "value_error")),
        "loc": [str(part) for part in location] if isinstance(location, tuple | list) else [],
        # `msg` is generated by Pydantic from the constraint, not from the
        # value — except for a handful of parser errors, which are still
        # descriptions rather than echoes.
        "msg": str(error.get("msg", "Invalid value")),
    }


async def safe_validation_error_handler(request: Request, exc: Exception) -> JSONResponse:
    errors = exc.errors() if isinstance(exc, RequestValidationError) else []
    return JSONResponse(
        status_code=422,
        content={"detail": [_safe_error(error) for error in errors]},
    )
